name: E2E Tests
on:
  push:
    branches:
      - main
      - canary
  pull_request:
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  e2e:
    runs-on: depot-ubuntu-22.04-8
    container:
      image: node:24-slim
      # credentials:
      #   username: ${{ vars.DOCKER_HUB_USERNAME || '' }}
      #   password: ${{ secrets.DOCKER_HUB_API_KEY || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - name: pnpm setup
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d
      - name: Install packages
        run: pnpm install --frozen-lockfile --no-cache
      - name: Run build
        run: pnpm build
      - name: Run E2E Tests
        run: pnpm test:e2e
