name: Lint
on:
  push:
    branches:
      - main
  pull_request:
permissions: 
  contents: read
  pull-requests: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: buildjet-2vcpu-ubuntu-2204
    container:
      image: node:24-slim
      # credentials:
      #   username: ${{ vars.DOCKER_HUB_USERNAME || '' }}
      #   password: ${{ secrets.DOCKER_HUB_API_KEY || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
      - name: pnpm setup
        uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c
      - name: Install packages
        run: pnpm install
      - name: Run Lint
        run: pnpm lint
        env:
          SKIP_ENV_VALIDATION: true
