name: PR Title Check
on:
  pull_request:
    types: [opened, edited, synchronize]
permissions: 
  pull-requests: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pr-title-check:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    container:
      image: node:24-slim
      # credentials:
      #   username: ${{ vars.DOCKER_HUB_USERNAME || '' }}
      #   password: ${{ secrets.DOCKER_HUB_API_KEY || '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Run PR title check
        run: |
          node .github/scripts/pr-title-check.js
